### ISSUE TITLE
Possible bug with Crops

### ISSUE THREAD

**Issue by tommykent1210** [ColonyPlusPlus/ColonyPlusPlus-mod#11]
Comment [on steam thread](http://steamcommunity.com/app/366090/discussions/8/1458455461483481740/?ctp=2)

> i've noticed a thing - if i plant too much potatoes, and in my case "to much" is like 150+, game starts to lag when this potato reaches its last grow stage. by lag i mean not an fps lag but server lag - npc start to teleport and my inventory messes up. it also does this only during a day. when monsters come it stops. i tryed to plant more vanilla wheat, like 4 10x10 fields to see if this is just how much things my rig can handle but it was fine.
>there is one more thing, after i harvest all potato it replants itself in a day or so. it just magicly does this for some reason forcing me to harvest it again.. because if i not -  it will start to lag again. magicly replanted potato spawns one by one, in its last grow stage. its not visual or something, i actualy get twise as much of it in the end

1. Possibly the crop manager should not check every 500ms, instead crops should announce their next update tick and the list is only processed then

2. Is there an extra cropstage being registered somewhere?

**Comment by tommykent1210** [comment]
>  when monsters come it stops

This specifically leads me to think cropupdates - they don't run at night!

**Comment by Dorky106** [comment]
Maybe make the crop take longer and let it update at night?
It should stop the non-stop updates after night ends.

**Comment by tommykent1210** [comment]
Well it only updates crops during the day as they don't grow at night. But I'm thinking of having each crop tell the updater "I don't need updating until X time" instead of the cropmanager checking every crop every 500ms

**Comment by tommykent1210** [comment]
I was also then going to have it check the current tickrate, and increase the time between updates if needed
