### ISSUE TITLE
Wiki/GH-Pages

### ISSUE THREAD

**Issue by tommykent1210** [ColonyPlusPlus/ColonyPlusPlus-mod#12]
The mod is getting pretty large now, and with new commands we should probably start a wiki

Thinks that need wiki articles:
- [x] commands
- [x] permissions
- [x] blocktypes

**Comment by Dorky106** [comment]
So which way are we doing this? GH-Pages or Wiki?

**Comment by tommykent1210** [comment]
GH-pages, theres a new GH-Pages branch. 

http://colonyplusplus.com/ builds from there
