### ISSUE TITLE
Move material generation to code

### ISSUE THREAD

**Issue by tommykent1210** [ColonyPlusPlus/ColonyPlusPlus-mod#15]
Currently the code is only used to generate ColonyPlusPlus materials - if we are going to check materials as SELF (as in issue #14) we need materials to be generated in code as there is no base API to check initialised materials (I think?)

**Comment by Dorky106** [comment]
In the middle of doing this right now.

**Comment by Dorky106** [comment]
All the material data has been changed over into code now.
