### ISSUE TITLE
Folder conflicts

### ISSUE THREAD

**Issue by Dadadah** [ColonyPlusPlus/ColonyPlusPlus-mod#2]
The project has folders that have the same name, but with different caps.
This causes a problem on windows machines.

**Comment by Dadadah** [comment]
Proposed Solution:
Merge Blocks and blocks
Merge Items and items.
This will probably have to be done on a unix based machine. I can supply if needed.

**Comment by tommykent1210** [comment]
It doesn't cause issues but I will change it for QOL. Visual Studio should be able to use namespaces without folder structure in general.

The main issue is getting Git to accept folder cases though - that one is hard... xD

**Comment by Dadadah** [comment]
I'll go ahead and attempt to fix it, then submit a pull request later today.

**Comment by Dorky106** [comment]
@Dadadah Just remember you also have our updates being pushed out often as well to deal with too.  Though I'm hoping to have the last one from me done before the next mod update done in the next hour or two.  Other than that I probably wont change anything unless someone submits a bug.
