### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by Dadadah** [ColonyPlusPlus/ColonyPlusPlus-mod#34]
If this mod is going to be like the modloader or forge of Colony Survival then we're gonna need excellent documentation! We should keep this in mind when we add new features.

**Comment by tommykent1210** [comment]
http://colonyplusplus.com/commands/

The main repo ColonyPlusPlus/ColonyPlusPlus has a docs folder that can be used to add new documentation pages pretty easily. These are built through GitHub Pages.
