### ISSUE TITLE
TP/TP request Command

### ISSUE THREAD

**Issue by Dadadah** [ColonyPlusPlus/ColonyPlusPlus-mod#47]
/tp dadadah
cheat.tp permission
/tphere dadadah
cheat.tphere
/tpr dadadah
tprequest
/tprhere dadadah
tprequest.here

**Comment by tommykent1210** [comment]
/teleport is actually already in the base game, but I'm not sure if it allows teleporting to other users

**Comment by Dadadah** [comment]
I was not aware of this until after I posted this issue. Though it would help to have a tprequest for users who have no permissions.

**Comment by tommykent1210** [comment]
Hmmm, maybe. We should definitely look into if players can teleport to other players or not
