### ISSUE TITLE
Anti-Griefing

### ISSUE THREAD

**Issue by Dorky106** [ColonyPlusPlus/ColonyPlusPlus-mod#56]
Well the onblockchange callback is in the API, so we can get to adding the anti-griefing feature into the mod for servers.

- [x] Claimed Chunks
- [x] Spawn
- [x] Permissions

**Comment by tommykent1210** [comment]
How is permissions/config coming along @Dorky106 ?

**Comment by Dorky106** [comment]
Permissions now work correctly so this feature is now finished.
