### ISSUE TITLE
Configuration Refactoring

### ISSUE THREAD

**Issue by tommykent1210** [ColonyPlusPlus/ColonyPlusPlus-mod#60]
Configuration should use objects and the "dot" notation

so "rotatingbanner.enabled" will map to:

```
"rotatingbanner": {
    "enabled": true
}
```

**Comment by tommykent1210** [comment]
Seems to be done, requires testing

**Comment by Dorky106** [comment]
> Seems to be done, requires testing
Nope getting errors :P 
It is almost done however, just going to build and test it out along with spawn protection
